login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: atamai_refinery
  <<: *login

test: &test
  database: atamai_refinery_test
  <<: *login
 
production:
  <<: *login
  database: atamai_refinery
 