login: &login
  adapter: mysql2
  host: localhost
  username: root
  password:

development: &development
  database: atamai_sales
  <<: *login

test: &test
  database: atamai_sales_test
  <<: *login
